#服务端口
server:
  port: 9092
#mybatis配置
mybatis:
  mapperLocations: classpath:mybatis/*.xml
#日志
logging:
  level:
   com.ll: debug
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/wages_manager?autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: lazy24
    driver-class-name: com.mysql.jdbc.Driver